application: trinfactor3
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /images
  static_dir: static/images



- url: /google0647a12ffa22793f\.html
  static_files: templates/google0647a12ffa22793f.html
  upload: templates/google0647a12ffa22793f\.html


- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest