from login import *
from logout import *
from mainpage import *
from newPost import *
from signup import *
from welcome import *
from firmware import *
from Hardware import *
from contact import *
from faq import *
from purchase import *
